Add documentation for Tekton support
kubesphere/ks-devops pull request #201
Opened 2021-08-23 08:39 UTC by flamywhale

Add documentation for Tekton support including usage , design and implementation details

2021-08-24 01:10 UTC, LinuxSuRen requested changes
Thanks for your great document. But there are some typos you need to take a look it.

2021-08-24 01:10 UTC, LinuxSuRen commented on docs/tekton-support.md
> +1. Setup a clean kubernetes cluster (v1.19.8 is **recommended**) using [kind](https://kind.sigs.k8s.io/), [kubectl](https://kubernetes.io/docs/reference/kubectl/overview/) or [kk](https://github.com/
`kubernetes` -> `Kubernetes`

2021-08-24 01:10 UTC, LinuxSuRen commented on docs/tekton-support.md
> +* The core logic of reconcile Pipeline crd resources is as follows:
`crd` -> `CRD`

2021-08-24 03:42 UTC, flamywhale commented on docs/tekton-support.md
> +1. Setup a clean kubernetes cluster (v1.19.8 is **recommended**) using [kind](https://kind.sigs.k8s.io/), [kubectl](https://kubernetes.io/docs/reference/kubectl/overview/) or [kk](https://github.com/
OK.

2021-08-24 03:43 UTC, flamywhale commented on docs/tekton-support.md
> +* The core logic of reconcile Pipeline crd resources is as follows:
Okay.

2021-08-24 07:47 UTC, LinuxSuRen reviewed
/lgtm

2021-08-24 07:48 UTC, LinuxSuRen commented
/cc @kubesphere/sig-devops

2021-08-25 06:26 UTC, JohnNiang commented
/lgtm

2021-08-25 06:28 UTC, JohnNiang commented
/lgtm

2021-08-25 06:30 UTC, merged