Provide more guide document for the potential contributors
kubesphere/ks-devops pull request #213
Opened 2021-09-01 14:30 UTC by LinuxSuRen

fix https://github.com/kubesphere/ks-devops/issues/211

This PR can explain itself due to it is documentation contribution.

## Desired reviewers
@JohnNiang @FeynmanZhou @AbdelouahabMbarki

2021-09-01 14:54 UTC, JohnNiang commented on README.md
> +  kk create cluster
Please note that this step only installs Kubernetes, not KubeSphere.

2021-09-01 14:54 UTC, JohnNiang commented on docs/cli.md
> +ks pip create --ws simple --template java --project default --skip-check -b good
Before we use ks, I suggest introducing `ks` from `docs/installation.md#kubesphere-cli`.

2021-09-01 20:20 UTC, AbdelouahabMbarki commented on docs/installation.md
> +k3d is a little helper to run Rancher Lab's [k3s](https://github.com/k3s-io/k3s) in Docker.
link to [k3d](https://github.com/rancher/k3d)  project

2021-09-01 20:20 UTC, AbdelouahabMbarki commented on docs/installation.md
> +kind is a tool for running local Kubernetes clusters using Docker container `nodes`.
ink to [kind](https://github.com/kubernetes-sigs/kind) project

2021-09-01 20:27 UTC, AbdelouahabMbarki reviewed
great ! i have left some comment

2021-09-03 10:22 UTC, AbdelouahabMbarki requested changes

2021-09-03 10:22 UTC, AbdelouahabMbarki commented on docs/installation.md
> +[k3d]((https://github.com/rancher/k3d)) is a little helper to run Rancher Lab's [k3s](https://github.com/k3s-io/k3s) in Docker.
typo()

2021-09-03 10:30 UTC, AbdelouahabMbarki approved these changes
/lgtm

2021-09-05 13:35 UTC, JohnNiang commented
Please resolve the conflicting files first.

2021-09-06 02:24 UTC, merged