Fix the wrong using of paging parameter start
kubesphere/ks-devops pull request #280
Opened 2021-09-28 12:52 UTC by LinuxSuRen

fix https://github.com/kubesphere/ks-devops/issues/279

Container image for the test purpose:
```
surenpi/devops-apiserver:dev-v3.2.0-alpha.0-b60b654
```

2021-09-28 15:16 UTC, JohnNiang requested changes

2021-09-28 15:16 UTC, JohnNiang commented on pkg/apiserver/query/types_test.go
> +}
New line needed at the end of file.

2021-09-29 01:04 UTC, LinuxSuRen commented on pkg/apiserver/query/types_test.go
> +}
Done

2021-09-29 01:27 UTC, JohnNiang commented
/lgtm

2021-09-29 01:30 UTC, merged