Fix the potential panic with git multi-branch source XML parse
kubesphere/ks-devops pull request #370
Opened 2021-11-23 08:24 UTC by LinuxSuRen

2021-11-23 08:55 UTC, JohnNiang requested changes
Please try to add some unit tests for this PR.

2021-11-24 02:42 UTC, LinuxSuRen commented
> Please try to add some unit tests for this PR.

Of course. Done.

2021-11-24 02:46 UTC, JohnNiang requested changes

2021-11-24 02:46 UTC, JohnNiang commented on pkg/client/devops/jenkins/pipeline_internal_test.go
> +</org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject>`
Newline needed.

2021-11-24 03:23 UTC, LinuxSuRen commented on pkg/client/devops/jenkins/pipeline_internal_test.go
> +</org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject>`
Done.

2021-11-24 03:28 UTC, JohnNiang approved these changes
/lgtm

2021-11-24 03:28 UTC, JohnNiang commented
/label tide/merge-method-squash

2021-11-24 03:32 UTC, merged