Fix the problem that could not proceed or break the pipeline created by others
kubesphere/ks-devops pull request #408
Opened 2021-12-09 08:45 UTC by JohnNiang

### What this PR dose

Refine approvable check logic, which `approvableCheck` requires the users who have PipelineRun management permission to approve a PipelineRun. If the particular submitters exist, we also restrict the users who are in the particular submitters.

### Why we need it

Since v3.2.0, ks-devops was separated from KubeSphere, which led to a problem that ks-devops could not obtain permissions for currently logging in user, so that we would not determine whether the user has sufficient permission to approve a PipelineRun. So we changed the approvable check logic to adapt the problem.

Please note that our APIs are protected by `ks-apiserver` based on RBAC.

### Which issue this PR fix

Fixes #407 

### Steps to test

Docker image for test:

```bash
docker.io/johnniang/devops-apiserver:dev-v3.2.1-rc.3-66a2d71
```

1. Create a Workspace, DevOps Project
2. Create two roles for the DevOps Project with permissions Pipeline management only and Pipeline viewing only respectively
3. Create two accounts (e.g.: tester-a and tester-b) and assign two roles to them respectively
4. Create a Pipeline via admin account with Jenkinsfile as below:
    ```groovy
    pipeline {
        agent none
        stages {
            stage('Example') {
                input {
                    message "Should we continue?"
                    ok "Yes, we should."
                    submitter ""
                    parameters {
                        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                    }
                }
                steps {
                    echo "Hello, ${PERSON}, nice to meet you."
                }
            }
        }
    }
    ```
1. Run the Pipeline multi times using admin account
2. Try to approve the Pipeline with three account
3. Change the submitter and try again

/kind bug
/cc @kubesphere/sig-devops 
/milestone v3.2

2021-12-09 10:46 UTC, LinuxSuRen requested changes

2021-12-09 10:46 UTC, LinuxSuRen commented on pkg/kapis/devops/v1alpha2/devops.go
> +				step.Approvable = step.Input.Approvable(userInfo.GetName())
What happens if there is a user A who is the owner of this Pipeline, and A is not a submitter. In this case, A will not be able to approve or reject it.

IMO, it is weird.

2021-12-09 10:46 UTC, LinuxSuRen commented on pkg/kapis/devops/v1alpha2/devops.go
> +		err = fmt.Errorf("you have no permission to approve this pipeline run")
`pipeline run` or `pipelinerun`, or `pipeline run record`

We don't have a expression `pipeline run`

2021-12-09 14:19 UTC, JohnNiang commented
Hi @LinuxSuRen , I have done according your suggestions.

2021-12-10 07:48 UTC, LinuxSuRen reviewed
/lgtm

2021-12-10 07:49 UTC, LinuxSuRen commented
Please confirm if this PR should be cherry-pick into release-3.2

2021-12-10 07:49 UTC, JohnNiang commented
/cherry-pick release-3.2

2021-12-10 07:49 UTC, LinuxSuRen commented
/approve

2021-12-10 07:50 UTC, merged