Put the argocd application status to ks application
kubesphere/ks-devops pull request #497
Opened 2022-03-11 08:04 UTC by LinuxSuRen

### What type of PR is this?

### What this PR does / why we need it:
/kind feature

This feature can help us to get the application status. See the following test results:

```yaml
spec:
  argoApp:
    destination:
      namespace: default
      server: https://kubernetes.default.svc
    project: default
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: test
      repoURL: https://gitlab.com/LinuxSuRen1/argocd
      targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
status:
  argoApp: '{"conditions":[{"lastTransitionTime":"2022-03-11T07:47:54Z","message":"failed
    to sync cluster https://10.43.0.1:443: failed to load initial state of resource
    Namespace: namespaces is forbidden: User \"system:serviceaccount:default:argocd-application-controller\"
    cannot list resource \"namespaces\" in API group \"\" at the cluster scope","type":"ComparisonError"},{"lastTransitionTime":"2022-03-11T07:47:54Z","message":"failed
    to sync cluster https://10.43.0.1:443: failed to load initial state of resource
    Namespace: namespaces is forbidden: User \"system:serviceaccount:default:argocd-application-controller\"
    cannot list resource \"namespaces\" in API group \"\" at the cluster scope","type":"ComparisonError"}],"health":{"status":"Healthy"},"reconciledAt":"2022-03-11T07:47:54Z","sync":{"comparedTo":{"destination":{"namespace":"default","server":"https://kubernetes.default.svc"},"source":{"directory":{"jsonnet":{},"recurse":true},"path":"test","repoURL":"https://gitlab.com/LinuxSuRen1/argocd","targetRevision":"HEAD"}},"status":"Unknown"}}'
```

### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:

Please check the following list before waiting reviewers:

- [ ] Already committed the CRD files to [the Helm Chart](https://github.com/kubesphere-sigs/ks-devops-helm-chart/) if you created some new CRDs
- [ ] Already [added the permission](https://github.com/kubesphere/ks-installer/blob/9e063b085a0e43fdb3d0d9e3e7f4149146f14b9c/roles/ks-core/prepare/files/ks-init/role-templates.yaml) for the new API
- [ ] Already added the RBAC markers for the new controllers

### Does this PR introduce a user-facing change??

```release-note
None
```

2022-03-11 10:00 UTC, JohnNiang commented on pkg/api/gitops/v1alpha1/application.go
> +	Status ApplicationStatus `json:"status,omitempty"`
How about adding the status fields as subresource? Please refer to https://book.kubebuilder.io/reference/generating-crd.html?highlight=//+kubebuilder:subresource:status#subresources

2022-03-11 10:00 UTC, JohnNiang commented on controllers/argocd/argocd-application-status-controller.go
> +//+kubebuilder:rbac:groups=argoproj.io,resources=applications,verbs=get;list
Don't forget adding the rbac config if you accept subresource suggestion below:
```go
//+kubebuilder:rbac:groups=gitops.kubesphere.io,resources=applications/status,verbs=get;update;patch
```

2022-03-11 10:45 UTC, JohnNiang commented on pkg/api/gitops/v1alpha1/application.go
> +	Status ApplicationStatus `json:"status,omitempty"`
BTW, this won't block this PR from merging by other reviewers.

2022-03-14 01:00 UTC, LinuxSuRen commented on controllers/argocd/argocd-application-status-controller.go
> +			err = r.Update(ctx, app.DeepCopy())
Good catch!

2022-03-14 06:08 UTC, JohnNiang requested changes
Hi @LinuxSuRen , please execute `make manifests` first after you add subresource.

2022-03-14 06:16 UTC, JohnNiang approved these changes
/lgtm

2022-03-14 06:24 UTC, merged